version: '3'

services:
  my-site:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/
      - /tmp/:/tmp/
    ports:
      - 8081:8081
    env_file: env
# TODO: Create a log file