CREATE TABLE flask_mail(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	message VARCHAR(250) NOT NULL,
	subtime DATETIME NOT NULL,
	ip INT UNSIGNED,
	PRIMARY KEY (id)
);